pages:
  tags:
    - pages
    - docker
  image: registry.math.unistra.fr/formation-info/gitlab-pages:debian-pandoc
  script:
    - pandoc -c pandoc.css --title-prefix="GitLab Pages" -H head.html -t html5 -s README.md -o index.html
    - mkdir public
    - cp logoIRMA.gif pandoc.css index.html tanuki.ico public/
  artifacts:
    paths:
      - public
